alter table tex_event_content drop foreign key fk_user_id;
alter table tex_investor drop foreign key FK9dm3ydnef9532i8b30g4jqm9a;
alter table tex_investor drop foreign key FKken9mtpr6ey4j4pa1njhona8;
alter table tex_user drop foreign key fk_user_address_useraddress;
alter table tex_user_action drop foreign key FKbrwsj0i3pq7on1y7kb420h8eo;
alter table tex_user_action drop foreign key FK3ufvcju0b7h209u03qbhc5d91;
alter table tex_user_profile drop foreign key fk_user_profile_user;
drop table if exists tex_address;
drop table if exists tex_event_content;
drop table if exists tex_investor;
drop table if exists tex_user;
drop table if exists tex_user_action;
drop table if exists tex_user_profile;
create table tex_address (id varchar(255) not null, creation_date DATETIME(3) not null, last_modified_date DATETIME(3) not null, object_version integer, address_line1 varchar(255), address_line2 varchar(255), address_type varchar(16), city varchar(128), country varchar(64), mail_code varchar(10), state varchar(64), us_address bit, primary key (id));
create table tex_event_content (id varchar(255) not null, creation_date DATETIME(3) not null, last_modified_date DATETIME(3) not null, object_version integer, approval_status varchar(32), endorsement bigint, file_size bigint, media_category varchar(255), name varchar(255), original_file_name varchar(255), published bit, published_date datetime, video_category varchar(255), event_image_path varchar(255), event_logLine varchar(255), event_title varchar(255), event_video_path varchar(255), isArchived bit, isLiveVideo bit, media_id varchar(255), video_description varchar(255), video_length bigint, user_id varchar(255), primary key (id));
create table tex_investor (id varchar(255) not null, creation_date DATETIME(3) not null, last_modified_date DATETIME(3) not null, object_version integer, funds_Invested double precision, userInvestor_id varchar(255), video_id varchar(255), primary key (id));
create table tex_user (id varchar(255) not null, creation_date DATETIME(3) not null, last_modified_date DATETIME(3) not null, object_version integer, accepted_tou bit, account_status varchar(16), dial_code varchar(16), email varchar(128), first_name varchar(20) not null, gender varchar(2), is_artist bit, account_deleted bit, email_verified bit, is_fan bit, is_Investor bit, is_talent bit, last_name varchar(20) not null, locale varchar(30), mobile varchar(30), password varchar(255), phone varchar(30), random_salt varchar(255), reset_password bit, token varchar(255), user_name varchar(255) not null, user_type varchar(16), address_id varchar(255), primary key (id));
create table tex_user_action (id varchar(255) not null, creation_date DATETIME(3) not null, last_modified_date DATETIME(3) not null, object_version integer, comment varchar(255), endorse bit, is_Following bit, rating integer, userFan_id varchar(255), video_id varchar(255), primary key (id));
create table tex_user_profile (id varchar(255) not null, creation_date DATETIME(3) not null, last_modified_date DATETIME(3) not null, object_version integer, cover_image varchar(1024), display_lastname bit, donation_recieved double precision, facebook_followers bigint, facebook_url varchar(1024), followers bigint, following bigint, imdb_url varchar(1024), industry bigint, instagram_followers bigint, instagram_url varchar(1024), investments double precision, money_earned double precision, number_of_views bigint, photo_url varchar(1024), profile_image varchar(1024), realtime_trending double precision, stars double precision, twitter_followers bigint, twitter_url varchar(1024), user_endorsement bigint, wikisite_url varchar(1024), user_id varchar(255), primary key (id));
alter table tex_event_content add constraint fk_user_id foreign key (user_id) references tex_user (id);
alter table tex_investor add constraint FK9dm3ydnef9532i8b30g4jqm9a foreign key (userInvestor_id) references tex_user (id);
alter table tex_investor add constraint FKken9mtpr6ey4j4pa1njhona8 foreign key (video_id) references tex_event_content (id);
alter table tex_user add constraint fk_user_address_useraddress foreign key (address_id) references tex_address (id);
alter table tex_user_action add constraint FKbrwsj0i3pq7on1y7kb420h8eo foreign key (userFan_id) references tex_user (id);
alter table tex_user_action add constraint FK3ufvcju0b7h209u03qbhc5d91 foreign key (video_id) references tex_event_content (id);
alter table tex_user_profile add constraint fk_user_profile_user foreign key (user_id) references tex_user (id);
